In [1]:
import numpy as np

In [4]:
asian_countries = np.array(['india', 'pakistan', 'china', 
                            'myanmar','sri_lanka', 'nepal', 'bhutan', 'afghanisthan'])

In [5]:
asian_countries

array(['india', 'pakistan', 'china', 'myanmar', 'sri_lanka', 'nepal',
       'bhutan', 'afghanisthan'], dtype='<U12')

In [6]:
asian_countries.reshape(2,2,2)

array([[['india', 'pakistan'],
        ['china', 'myanmar']],

       [['sri_lanka', 'nepal'],
        ['bhutan', 'afghanisthan']]], dtype='<U12')

# Inferred

In [8]:
asian_countries.reshape(2,4)

array([['india', 'pakistan', 'china', 'myanmar'],
       ['sri_lanka', 'nepal', 'bhutan', 'afghanisthan']], dtype='<U12')

In [7]:
asian_countries.reshape(-1,4)

array([['india', 'pakistan', 'china', 'myanmar'],
       ['sri_lanka', 'nepal', 'bhutan', 'afghanisthan']], dtype='<U12')

In [9]:
asian_countries.reshape(4,-1)

array([['india', 'pakistan'],
       ['china', 'myanmar'],
       ['sri_lanka', 'nepal'],
       ['bhutan', 'afghanisthan']], dtype='<U12')

In [11]:
a = np.arange(100).reshape(2,2,5,5)
a

array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19],
         [20, 21, 22, 23, 24]],

        [[25, 26, 27, 28, 29],
         [30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39],
         [40, 41, 42, 43, 44],
         [45, 46, 47, 48, 49]]],


       [[[50, 51, 52, 53, 54],
         [55, 56, 57, 58, 59],
         [60, 61, 62, 63, 64],
         [65, 66, 67, 68, 69],
         [70, 71, 72, 73, 74]],

        [[75, 76, 77, 78, 79],
         [80, 81, 82, 83, 84],
         [85, 86, 87, 88, 89],
         [90, 91, 92, 93, 94],
         [95, 96, 97, 98, 99]]]])

In [16]:
a.reshape(-1,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

- a = x+y+z

In [17]:
a.reshape(5,-1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29],
        [30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49],
        [50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]],

       [[60, 61],
        [62, 63],
        [64, 65],
        [66, 67],
        [68, 69],
        [70, 71],
        [72, 73],
        [74, 75],
        [76, 77],
        [78, 79]],

       [[80, 81],
        [82, 83],
        [84, 85],
        [86, 87],
        [88, 89],
        [90, 91],
        [92, 93],
        [94, 95],
        [96, 97],
        [98, 99]]])

# Transpose of Matrix

- a = n*m
- b = m*n

In [22]:
a2 = np.arange(18).reshape(6,-1)
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [23]:
a2.T

array([[ 0,  3,  6,  9, 12, 15],
       [ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17]])

# Ravel

In [24]:
# converts any dimensional array to 1d

In [25]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

# Flatten

In [26]:
a2.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

# Basic Operations on Array

In [52]:
a = np.array([10,20,30,40])
b = np.array([5,10,15,20])

In [33]:
# Addition
a + b

array([15, 30, 45, 60])

In [34]:
# sub
a-b

array([ 5, 10, 15, 20])

In [53]:
# mul 
a*2

array([20, 40, 60, 80])

In [54]:
a*b

array([ 50, 200, 450, 800])

In [35]:
# Div
a/b

array([2., 2., 2., 2.])

In [36]:
a%2

array([0, 0, 0, 0])

In [37]:
b%2

array([1, 0, 1, 0])

In [39]:
a

array([10, 20, 30, 40])

In [38]:
a<20

array([ True, False, False, False])

In [41]:
a[a>20]

array([30, 40])

In [42]:
a.sum()

100

In [44]:
# Operations on different dim arrays are not possible

In [48]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3,4], [4,5,6,7]])

In [50]:
print(a.shape)
print(b.shape)

(2, 3)
(2, 4)


In [51]:
a+b

ValueError: operands could not be broadcast together with shapes (2,3) (2,4) 

In [55]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,4],[2,5],[3,6]])

In [56]:
print(a.shape)
print(b.shape)

(2, 3)
(3, 2)


In [58]:
c = a.dot(b)

In [59]:
c.shape

(2, 2)

In [60]:
array_a = np.array([21,10,15,20])

In [62]:
# compute the sum of all elements
array_a.sum()

66

In [63]:
# find the minimum element in the array
array_a.min()

10

In [64]:
# find the maximum element in the array
array_a.max()

21

In [65]:
array_b = np.arange(24).reshape(4,6)
array_b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [66]:
# find the sum
array_b.sum()

276

- axis = 0 ---- columns
- axis = 1 ----rows

In [67]:
# sum of all the rows
array_b.sum(axis=1)

array([ 15,  51,  87, 123])

In [68]:
# sum of all the columns
array_b.sum(axis=0)

array([36, 40, 44, 48, 52, 56])

In [69]:
# find the min in array
array_b.min(axis=1)

array([ 0,  6, 12, 18])

In [70]:
array_b.min(1)

array([ 0,  6, 12, 18])

In [71]:
array_b.min(0)

array([0, 1, 2, 3, 4, 5])

In [72]:
# find the max in array
array_b.max(axis=1)

array([ 5, 11, 17, 23])

In [73]:
array_b.max(1)

array([ 5, 11, 17, 23])

In [74]:
array_b.max(0)

array([18, 19, 20, 21, 22, 23])

# Indexing and Slicing

In [77]:
a = np.arange(5)**2
a

array([ 0,  1,  4,  9, 16])

In [78]:
a[1]

1

In [79]:
a[4]

16

In [80]:
a[-1]

16

In [81]:
a[-2]

9

In [82]:
# Slicing

In [83]:
a

array([ 0,  1,  4,  9, 16])

In [84]:
a[2:5]

array([ 4,  9, 16])

In [85]:
a[::-1]

array([16,  9,  4,  1,  0])

In [86]:
a[-1:-4:1]

array([], dtype=int64)

# Two Dimensional array

In [87]:
b = np.arange(6).reshape(2,3)

In [88]:
b

array([[0, 1, 2],
       [3, 4, 5]])

# Indexing

In [89]:
# Get 4
b[1,1]

4

In [90]:
b[1][1]

4

In [91]:
b[0,2]

2

In [92]:
b[0,-1]

2

# Slicing in 2D arrays

In [93]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [94]:
a[1][2:4]

array([7, 8])

In [95]:
a[1,2:4]

array([7, 8])

In [ ]:
-18,19

In [96]:
a[3:,3:] 

array([[18, 19],
       [23, 24]])

In [100]:
a[::,2::2]

array([[ 2,  4],
       [ 7,  9],
       [12, 14],
       [17, 19],
       [22, 24]])

In [105]:
a[::2,::]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [101]:
a[::2,::]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

In [102]:
a[::,2::2]

array([[ 2,  4],
       [ 7,  9],
       [12, 14],
       [17, 19],
       [22, 24]])

In [98]:
a[::2,2::2]

array([[ 2,  4],
       [12, 14],
       [22, 24]])

In [99]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [108]:
a < 6

array([[ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [107]:
a[a<6]

array([0, 1, 2, 3, 4, 5])

In [109]:
# how many values are less than 6

In [110]:
np.sum(a<6)

6

In [111]:
len(a[a<6])

6

In [115]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [116]:
# for 2D arrays
a[3:]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [113]:
a[3:][3:]

array([], shape=(0, 5), dtype=int64)

In [119]:
a1 = np.array([0,0,0,0])
a1

array([0, 0, 0, 0])

In [114]:
a[3:,3:]

array([[18, 19],
       [23, 24]])

In [120]:
# Iterating over a numpy array
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [121]:
for i in a :
    print(i)

1
2
3
4
5


In [124]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [125]:
for i in a :
    print(i)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]
[20 21 22 23 24]


In [126]:
for i in a :
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [127]:
for i in a.ravel():
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24


In [128]:
for i in a.flatten():
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
